name: Build and Deploy to Develop
on:
  push:
    branches:
      - develop

#cancel previous runs for this ref
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  
  call-workflow-deploy:
    uses: ./.github/workflows/deploy-site.yml
    with:
      environment: Dev
    secrets: inherit